config/routes.rb
Lollaby::Application.routes.draw do
  resources :quotes

  devise_for :users

  root :to => "quotes#index"

end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  has_many :quotes

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController

  before_filter :authenticate_user!, :except => [:show, :index]

  # GET /quotes
  # GET /quotes.xml
  def index
    @quotes = Quote.all
    

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @quotes }
    end
  end

  # GET /quotes/1
  # GET /quotes/1.xml
  def show
    @quote = Quote.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @quote }
    end
  end

  # GET /quotes/new
  # GET /quotes/new.xml
  def new
    @quote = Quote.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @quote }
    end
  end

  # GET /quotes/1/edit
  def edit
    @quote = Quote.find(params[:id])
  end

  # POST /quotes
  # POST /quotes.xml
  def create
    @quote = Quote.new params[:quote].merge(:user_id => current_user.id)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to(@quote, :notice => 'Quote was successfully created.') }
        format.xml  { render :xml => @quote, :status => :created, :location => @quote }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @quote.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /quotes/1
  # PUT /quotes/1.xml
  def update
    @quote = Quote.find(params[:id])

    respond_to do |format|
      if @quote.update_attributes(params[:quote])
        format.html { redirect_to(@quote, :notice => 'Quote was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @quote.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.xml
  def destroy
    @quote = Quote.find(params[:id])
    @quote.destroy

    respond_to do |format|
      format.html { redirect_to(quotes_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>cit / quote database</title>
  <meta charset="utf-8" />
  <script src="/javascripts/typeface.js" type="text/javascript"></script>
  <script src="/javascripts/gentilis_bold.typeface.js" type="text/javascript"></script>
  <%= stylesheet_link_tag ("style") %>
  <%= csrf_meta_tag %>
</head>
	<body>
		<div id="page">
			<div id="header">
				<a href="#home"><div id="logo" class="typeface-js" style="font-family:gentilis;font-size:50px;font-weight:bold; color:#ffffff;">cit</div></a>
				<div id="definition"><strong>/sɪt/</strong> <i>a passage cited; quotation.</i></div>
				<div id="navigation"><% if user_signed_in? %>  <%= current_user.email %> | 
    <%= link_to "Sign out", destroy_user_session_path %>  
  <% else %>  
    <%= link_to "Sign up", new_user_registration_path %> or  
    <%= link_to "Sign in", new_user_session_path %>  
  <% end %>  </div>
			</div>

<%= yield %>
		</div>
		<div id="footer">? lol</div>
</body>
</html>

app/views/quotes/_form.html.erb
<%= form_for(@quote) do |f| %>
  <% if @quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% @quote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cit %><br />
    <%= f.text_area :cit %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>
  <div class="field">
    <%= f.label :source %><br />
    <%= f.text_field :source %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<h1>Editing quote</h1>

<%= render 'form' %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/index.html.erb
<div id="content">

<% @quotes.each do |quote| %>

	<div class="entry">
    <%= image_tag "http://www.gravatar.com/avatar.php?gravatar_id=#{Digest::MD5.hexdigest(quote.user.email).to_s}&s=50", :class => "avatar" %>
    &#8220;<%= quote.cit %>&#8221;<br><br>
                      ~<%= quote.source %>
<!--    <td><%= link_to 'Show', quote %></td>
    <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
    <td><%= link_to 'Destroy', quote, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr> !-->
  <div class="divider">&nbsp;</div>
<% end %>

<br />

 <%= link_to 'New Quote', new_quote_path %>!
 
<div class="clear">&nbsp;</div>

app/views/quotes/new.html.erb
<h1>New quote</h1>

<%= render 'form' %>

<%= link_to 'Back', quotes_path %>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cit:</b>
  <%= @quote.cit %>
</p>

<p>
  <b>Source:</b>
  <%= @quote.source %>
</p>


<%= link_to 'Edit', edit_quote_path(@quote) %> |
<%= link_to 'Back', quotes_path %>